### ISSUE TITLE
Not an issue, more like a feature request

### ISSUE THREAD

**Issue by manderso7** [stdevel/satprep#21]
I'm not sure if I'm putting this in the right place, hopefully I am.
Would it be possible to add to the pdf/diff that gets created, the CVE # that the installed patch references? That's one of the requirements of my security report.
If this is the wrong way to go about asking for this, please advise and I'll post correctly.
Thanks very much!

**Comment by stdevel** [comment]
Hi manderso7,
I didn't forget your request. I'm very busy with other things currently.

**Comment by manderso7** [comment]
Nice of you to email, but I realize it's not your day job. Looking forward to the end result, thanks.

**Comment by stdevel** [comment]
Hello manderso7,
I'm sorry, but this feature won't be implemented as development on Spacewalk and Red Hat Satellite 5.x have stalled. I also migrated from Spacewalk to Foreman/Katello and started rewriting this toolkit for the new management software. In Foreman/Katello, implementing this will be much easier.

Best regards,
Christian!
