### ISSUE TITLE
Script for doing complex maintenance

### ISSUE THREAD

**Issue by stdevel** [stdevel/satprep#24]
As **satprep** already offers the possibility to (_un-_)schedule downtimes and create/remove VM snapshots it would be great if it does more complex maintenance in an automated way. I think about nasty things like:
- patch applications
- restart particular daemons
- execute third-party scripts
- force rechecking monitoring
- validating that required services are "_OK_" in Nagios, Icinga and Shinken

**Comment by novonilc** [comment]
Patching applications is one thing we are looking forward to.. this would really help us in building a right strategy.

**Comment by novonilc** [comment]
Can you include support for Solar winds.. is possible

**Comment by stdevel** [comment]
I think I will go for a "*scriptable installation task*" approach - so for particular servers there might be scripts that can be handed to the host. Makes it easier for me as I don't need to focus on particular applications - the administrator can do this as he knows his infrastructure best. :grin:

**Comment by stdevel** [comment]
Ahh.. just saw that SolarWinds is a monitoring tool. Sorry, thought you were talking about an application on a managed Linux system.
Well - I'm not familiar with it. Do you know whether this tool is just a GUI for Nagios? Looks very similiar to Nagios.

Best regards!

**Comment by stdevel** [comment]
Won't do this as I started rewriting this toolkit.
