### ISSUE TITLE
Exclude systems and groups in satprep_snapshot.py

### ISSUE THREAD

**Issue by stdevel** [stdevel/satprep#45]
It would be great to have the possibility to exclude systems and groups in `satprep_snapshot.py`. Parameter ideas:
- `-e` / `--exclude`
- `-g` / `--group`
- `-E` / `--exclude-group`
- `-H` / `--include-host`

**Comment by novonilc** [comment]
It would be great to have this. It is kind of must have for someone trying to do patch the non-prod machines first and then go to prod..

**Comment by stdevel** [comment]
Yeah, definitely! But for the dev/test and prod differentation you can also utilize the ``SYSTEM_PROD``custom info key and the ``--prod-only`` and ``--nonprod-only``parameters of ``satprep_snapshot.py``. See the wiki:
https://github.com/stdevel/satprep/wiki/simple-setup
https://github.com/stdevel/satprep/wiki/ainfo-satprep_prepare_maintenance

**Comment by novonilc** [comment]
Thanks

**Comment by stdevel** [comment]
Won't do this as I started rewriting this toolkit.
