### ISSUE TITLE
Getting clone error while cloning

### ISSUE THREAD

**Issue by novonilc** [stdevel/satprep#48]
Getting following issue while cloning. Can you please fix this.

ERROR:satprep_patch_freeze:Unable to clone base-channel: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: The channel parameter rhn-tools-rhel-x86_64-server-6 clone from 2015-12-03 is invalid. It must be at least 6 characters long, begin with a letter, and contain only lowercase letters, digits, '-', ' / ', '_' and '.'.  Also, it cannot begin with 'rhn', 'redhat', or 'red hat'.

**Comment by stdevel** [comment]
See also issue #46 (*will be fixed today ;o*)
