### ISSUE TITLE
satprep_prepare_maintenance.py is not working

### ISSUE THREAD

**Issue by novonilc** [stdevel/satprep#52]
# ./satprep_prepare_maintenance.py -k -a auth -g Test_for_satprep -K errata-snapshot-report-localhost-20151217-1433.csv
Haha, you're funny.

Can you have a look please

**Comment by novonilc** [comment]
[root@lyn-rhnsat-01 satprep-master]# ./satprep_prepare_maintenance.py -V errata-snapshot-report-localhost-20151217-1433.csv
Traceback (most recent call last):
  File "./satprep_prepare_maintenance.py", line 498, in <module>
    main(options)
  File "./satprep_prepare_maintenance.py", line 379, in main
    verify()
  File "./satprep_prepare_maintenance.py", line 51, in verify
    myLog = open(myPrefix+"_satprep.vlog", "r+")
IOError: [Errno 2] No such file or directory: '20151219_satprep.vlog'

**Comment by stdevel** [comment]
Is the user you're using for running the script allowed to create files in the directory?
Does this issue persist for you in the latest release of satprep?

**Comment by novonilc** [comment]
I am ruuning using root. I did not check the latest one. Can i run using
any other user than root ?

On Monday, 18 April 2016, Christian Stankowic <notifications@github.com>
wrote:

> Is the user you're using for running the script allowed to create files in
> the directory?
> Does this issue persist for you in the latest release of satprep?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stdevel/satprep/issues/52#issuecomment-211360401>
>


-- 
Sent from my iPhone

**Comment by stdevel** [comment]
As long as this user has the rights to write in the current directory and also to `/tmp` you can use any user. :)

**Comment by novonilc** [comment]
Thank you for your prompt reply :)

**Comment by stdevel** [comment]
You're welcome!

Let me know if you need further assistance.

Best regards!

**Comment by novonilc** [comment]
Sure will do. Thanks for all your help
